### ISSUE TITLE
请问支持电脑端安卓模拟器吗？

### ISSUE THREAD

**Issue by Dermitius** [hxdnshx/MAALimbusCompany#2]
如题，而且下载文件是1999的

**Comment by hxdnshx** [comment]
目前产物是对应于Limbus的，只是名字没改。等下一个赛季我一起改掉吧（sad

支持范围跟MAA主项目一致，你可以参考主项目的文档。

目前我自己用的MuMu12，可以正常工作（建议更新到最新版）

**Comment by hxdnshx** [comment]
你可以启动后执行README.md中所述的那些任务。
