### ISSUE TITLE
请教一些问题

### ISSUE THREAD

**Issue by AlterGu** [hxdnshx/MAALimbusCompany#4]
1. 可以开发自动镜牢吗
2. 线在刷取的时候自动选择lv20的  如果想选最高等级的(lv40)需要怎么操作？

**Comment by hxdnshx** [comment]
1. 目前这个项目的状态是仅对应新活动的自动刷取进行更新。镜牢方面可以考虑使用其他解决方案，如在项目介绍里提到的那些；或是自行进行开发；如果已有逻辑满足需要可以直接按照LICENSE 指定的方式使用。
2. 这个我检查一下；在下个版本修正。

**Comment by AlterGu** [comment]
感谢回答。
